agent: ppo
d_actor: [128,64]
lstm_seqential: [64,64]
recon_hidden: [64,64]
actor_params_hidden: [64,64]
decoder_params_hidden: [64,64]
latent_dim: 6
d_critic: 32
num_envs: 32
rollout_len: 256
sequence_length: null
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
norm_adv: false
clip_coef: 0.1
dist_model: ${experiment.combos.${experiment.choice}.dist_model}
run_mode: train

sample_distribution: ${experiment.combos.${experiment.choice}.sample_distribution}

ent_coef: 
  init_value: 0.3
  end_value: 0.1
  transition_steps: 1000
  power: 1

stability_coef: 
  init_value: 0.06
  end_value: 0
  transition_steps: 1000
  power: 2

vf_coef: 0.4
max_grad_norm: 0.5
optimizer: 
  learning_rate: 
    init_value: 0.001 #2.5e-4
    end_value: 0.001 #2.5e-4
    transition_steps: 1000
    power: 1
defaults:
  - _self_
  - seq_model: lstm