# task: cor_gmm
# name: cor_gmm
# env: cosine
# view_size: 2
# max_steps: null
# bounds: [-2, 2]
# max_episode_steps: 12
# batches: [1,1]
# action_dim: 3
# degree: 2
# batch_expand_hidden: [128, 64]
# batch_combine_hidden: [128, 64]
# step_expand_hidden: [128, 64]
# input_combine_hidden: [128, 64]

task: cor_gmm
name: cor_gmm
env: cosine
bounds: [-2, 2]
# These keys are set from the experiment combos:
batches: ${experiment.combos.${experiment.choice}.batches}
max_episode_steps: ${experiment.combos.${experiment.choice}.max_episode_steps}
total_episode_samples: 40
action_dim: 3
degree: 2
rank: 2
num_oscillations: 5
batch_expand_hidden: [16,32,64,32,16]
batch_combine_hidden: [16, 32,64,32,16]
step_expand_hidden: [16, 32,64,32,16]
input_combine_hidden: [16, 32,64,32,16]