task: full_params
name: full_params
env: cosine
bounds: [-2, 2]
# These keys are set from the experiment combos:
batches: ${experiment.combos.${experiment.choice}.batches}
max_episode_steps: ${experiment.combos.${experiment.choice}.max_episode_steps}
total_episode_samples: 40
action_dim: 3
degree: 2
rank: 2
num_oscillations: 5
random: true
batch_expand_hidden: [64, 128,]
batch_combine_hidden: [32, 64]
step_expand_hidden: [32, 64]
input_combine_hidden: [32, 64]
tag: no_tag