task: masked
name: masked
view_size: 2
max_steps: null
bounds: [-1, 1]
max_episode_steps: 12
batches: [1,1]
action_dim: 1
degree: 2
batch_expand_hidden: [64, 64]
batch_combine_hidden: [64, 64]
step_expand_hidden: [64, 64]
input_combine_hidden: [64, 64]