# name: ${experiment.combos.${experiment.choice}.name}
task: ${experiment.combos.${experiment.choice}.task}
pol_dist: ${experiment.combos.${experiment.choice}.pol_dist}
env_train: ${experiment.combos.${experiment.choice}.env_train}
env_test: ${experiment.combos.${experiment.choice}.env_test}

poly_env:  ${function_params.${experiment.combos.${experiment.choice}.poly_params}}
gaussian_env:  ${function_params.${experiment.combos.${experiment.choice}.gaussian_params}}
ackley_env:  ${function_params.${experiment.combos.${experiment.choice}.ackley_params}}
matern52_env:  ${function_params.${experiment.combos.${experiment.choice}.matern52_params}}
neg_abs_env: ${function_params.${experiment.combos.${experiment.choice}.neg_abs_params}}
branin_env: ${function_params.${experiment.combos.${experiment.choice}.branin_params}}
cosine_env: ${function_params.${experiment.combos.${experiment.choice}.cosine_params}}
egg_env: ${function_params.${experiment.combos.${experiment.choice}.egg_params}}
hartmann_env: ${function_params.${experiment.combos.${experiment.choice}.hartmann_params}}
matern52_kernel_env: ${function_params.${experiment.combos.${experiment.choice}.matern52_kernel_params}}
rbf_kernel_env: ${function_params.${experiment.combos.${experiment.choice}.rbf_kernel_params}}
# michalewicz_env: ${function_params.${experiment.combos.${experiment.choice}.michalewicz_params}}
rosenbrock_env: ${function_params.${experiment.combos.${experiment.choice}.rosenbrock_params}}
discrete_peaks_env: ${function_params.${experiment.combos.${experiment.choice}.discrete_peaks_params}}

matern32_env: ${function_params.${experiment.combos.${experiment.choice}.matern32_kernel_params}}
matern12_env: ${function_params.${experiment.combos.${experiment.choice}.matern12_kernel_params}}
rff_env: ${function_params.${experiment.combos.${experiment.choice}.rff_kernel_params}}
linear_env: ${function_params.${experiment.combos.${experiment.choice}.linear_kernel_params}}
polynomial_env: ${function_params.${experiment.combos.${experiment.choice}.polynomial_kernel_params}}
periodic_env: ${function_params.${experiment.combos.${experiment.choice}.periodic_kernel_params}}
white_env: ${function_params.${experiment.combos.${experiment.choice}.white_kernel_params}}
arc_cosine_env: ${function_params.${experiment.combos.${experiment.choice}.arc_cosine_kernel_params}}
exponential_env: ${function_params.${experiment.combos.${experiment.choice}.exponential_kernel_params}}
rational_quadratic_env: ${function_params.${experiment.combos.${experiment.choice}.rational_quadratic_kernel_params}}


function_types: []
bounds: ${experiment.combos.${experiment.choice}.bounds}
# These keys are set from the experiment combos:
batches: ${experiment.combos.${experiment.choice}.batches}
max_batches: -1
total_episode_samples: ${experiment.combos.${experiment.choice}.total_episode_samples}
max_episode_steps: -1
action_dim: ${experiment.combos.${experiment.choice}.action_dim}
degree: ${experiment.combos.${experiment.choice}.degree}
rank: ${experiment.combos.${experiment.choice}.rank}
num_oscillations: ${experiment.combos.${experiment.choice}.oscilations}
random: ${experiment.combos.${experiment.choice}.random}
batch_expand_hidden: [256, 512, 256]
batch_combine_hidden: [256, 512, 256]
step_expand_hidden: [256, 512, 256]
input_combine_hidden: [256, 512, 256]
tag: no_tag