tags: null
project_name: "cosine_tests"
run_name: "should be overriden"
seed: 55
steps: 500000
log_interval: 20000
eval_episodes: 1
eval_interval: 20000
use_wandb: true
defaults:
  - _self_
  - task: gen_gmm
  - trainer: ppo
