defaults:
  - _self_
  - task: gen_gmm
  - trainer: deep_ppo
  - experiment: combos   # loads config/experiment/combos.yaml

# Default experiment selection (can be overridden on the CLI)
experiment:
  choice: exp1

# Global settings
tags: null
project_name: "testing123"
run_name: ""
seed: 77
steps: 200000
log_interval: 1024
eval_episodes: 20
eval_interval: 100000
use_wandb: false

