defaults:
  - _self_
  - task: variable
  - trainer: variable_ppo
  - experiment: combos   # loads config/experiment/combos.yaml
  - function_params: funcs  # loads config/function_params/variable.yaml
# Default experiment selection (can be overridden on the CLI)
experiment:
  choice: test_jax


# Global settings
tags: null
project_name: ${experiment.combos.${experiment.choice}.project_name}
run_name: ""
seed: 77
steps: ${experiment.combos.${experiment.choice}.steps}
log_interval: 4096
eval_episodes: 3
eval_interval: 150000
use_wandb: true

